# Global Relayer configuration
global:
  privateKey: ""      # The privateKey of the account that will be submitting the packet relays
  logLevel: "info"
  blockDelay: 5       # Delay with which to process the chain blocks

  getter:
    interval: 5000    # Interval at which to poll the chains RPCs for new events
    maxBlocks: 1000   # Maximum number of blocks to query in a single call

  submitter:
    enabled: true
    newOrdersDelay: 1000        # Time to wait before processing new 'submission' orders
    retryInterval: 30000        # Time to wait before retrying a failed transaction
    processingInterval: 100     # Throttle for the Submitter main 'run' loop
    maxTries: 3                 # Maximum tries for a transaction
    maxPendingTransactions: 50  # Maximum number of transactions within the 'submit' pipeline.
    confirmations: 1            # Number of confirmations to deem that a transaction has been mined
    confirmationTimeout: 90000  # Timeout for a transaction to confirm

    lowBalanceWarning: "1000000000000000000"  # Balance below which a 'low balance' warning is emitted.
    balanceUpdateInterval: 50   # Number of transactions after which to update the Relayer balance from the rpc. 

    # Gas properties
    gasLimitBuffer:             # Extra gasLimit buffer. Customizable per AMB.
      default: 10000
      mock: 50000

    # EIP-1559 Transactions
    maxFeePerGas: "200000000000"                 # 'maxFeePerGas' set for all transactions (for chains that support eip-1559)

    maxAllowedPriorityFeePerGas: "100000000000"  # Upper bound to the 'maxPriorityFeePerGas' set on transactions (for chains that support eip-1559)
    maxPriorityFeeAdjustmentFactor: 1.05         # Decimal factor used to adjust the 'maxPriorityFeePerGas' returned by 'getFeeData()'. 
                                                 # The resulting value is set as the 'maxPriorityFeePerGas' property of the transaction
                                                 # if it is smaller than the configuration property 'maxAllowedPriorityFeePerGas' (if set).

    # Legacy Transactions
    maxAllowedGasPrice: "200000000000"           # Upper bound to the 'gasPrice' set on transactions (for chains that do not support eip-1559)
    gasPriceAdjustmentFactor: 1.05               # Decimal factor used to adjust the 'gasPrice' returned by 'getFeeData()'. The resulting 
                                                 # value is set as the 'gasPrice' property of the transaction if it is smaller than the 
                                                 # configuration property 'maxAllowedGasPrice' (if set).

    # All Transactions
    priorityAdjustmentFactor: 1.2                # Decimal factor used to adjust **all** the gas prices (including 'maxFeePerGas') for 
                                                 # priority transactions.

  persister:
    enabled: false
    postgresString: "postgresql://username:password@location/database?sslmode=require"


# AMBs configuration
ambs:
  - name: mock
    enabled: true   # Defaults to 'true' if the key is missing
    incentivesAddress: "0x0000006aA532b110f36f393887079b35F6C6979a"
    privateKey: ""

  - name: polymer
    incentivesAddress: "0x0000000000000000000000000000000000000000"

  - name: wormhole
    incentivesAddress: "0x000000731594E9be29E6c45Ab477034939053d4E"
    isTestnet: true


# Chain configuration
chains:

  - chainId: 80001 
    name: "Mumbai"
    rpc: "https://polygon-mumbai-pokt.nodies.app"

    blockDelay: 2
    # startingBlock   # The block number at which to start Relaying (not all AMB collectors may support this property)
    # stoppingBlock   # The block number at which to stop Relaying (not all AMB collectors may support this property)

    # Overrides
    getter:
      interval: 3000
    submitter:
      retryInterval: 3000

    # AMB configuration
    wormhole:
      wormholeChainId: 5
  

  - chainId: 11155111 
    name: "Sepolia"
    rpc: "https://eth-sepolia-public.unifra.io"
    wormhole:
      wormholeChainId: 10002
